version: 2
dependencies:
    cache_directories:
        - "~/.platformio"

    pre:
        - sudo pip install -U platformio

        # pre-install PlatformIO development platforms, they will be cached
        - platformio platform install atmelavr atmelsam espressif8266
jobs:
   build:
     docker:
       - image: circleci/python:2.7.12-stretch-browsers
     steps:
       - checkout
       - run: platformio ci --project-conf platformio.ini src --lib lib/prod-dbg