
dependencies:
    cache_directories:
        - "~/.platformio"
    pre:
        - sudo pip install -U platformio

        # pre-install PlatformIO development platforms, they will be cached
        - platformio platform install atmelavr atmelsam espressif8266

test:
    override:
        - platformio ci --project-conf platformio.ini src --lib lib/prod-dbg
