version: 2
dependencies:
    pre:
        - sudo pip install -U platformio

        # pre-install PlatformIO development platforms, they will be cached
        - platformio platform install atmelavr atmelsam espressif8266
test:
    override:
        - platformio ci src/button-test.cpp
